user: ajinkya
server: 10.129.26.36
host: 10.1.1.101
code: [opt] # [opt,base]
method: pepin # [pepin, naive, boundary]
pepin-eps: 0.1
pepin-delta: 0.1
pepin-seed: 42
experiment_folder: /home/ajinkya/experiments/pepin_diabetes_corrected
benchmark_dir: ./models/diabetes
gap: 2
precision: 2
bit_distance: 1 
num_cores: 1
max_parallel_jobs: 100
upload_code: true
compile: true
log_dir: "./experiment_results/logs"
baseline_log_dir: "./experiment_results/baseline_logs"
timeout: 1800 #seconds
memory_limit_gb: 4 #new parameter
random_seed: 42
num_features_to_sample: -1  # Number of features to randomly sample per model (set to -1 for all features)